SSHARE-13: updated script to not to use EXISTING

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -80,20 +80,22 @@ jobs:
     
     - name: Deploy Cross Account Roles Stack Set
       run: |
-        EXISTING=$(aws cloudformation describe-stack-set --stack-set-name ${{env.CROSS_ACCOUNT_STACK_SET_NAME}} --call-as DELEGATED_ADMIN --region ${{ env.AWS_REGION }} > /dev/null 2>&1)
-
-        if [-z "$EXISTING"]; then
+        # If it succeeds (0), it goes to 'else' (Update). 
+        # If it fails (non-zero), it goes to the first block (Create).
+        if ! aws cloudformation describe-stack-set --stack-set-name ${{env.CROSS_ACCOUNT_STACK_SET_NAME}} --call-as DELEGATED_ADMIN --region ${{ env.AWS_REGION }} > /dev/null 2>&1; then
           echo "StackSet does not exist. Creating..."
+          
+          # Capture ONLY the OperationId string
           OP_ID=$(aws cloudformation create-stack-set \
-          --stack-set-name ${{env.CROSS_ACCOUNT_STACK_SET_NAME}} \
-          --template-url https://deployment-template.s3.${{ env.AWS_REGION }}.amazonaws.com/cross-account-roles.yaml \
-          --output json \
-          --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
-          --permission-model SERVICE_MANAGED \
-          --auto-deployment Enabled=true,RetainStacksOnAccountRemoval=false \
-          --call-as DELEGATED_ADMIN \
-          --parameters ParameterKey=ToolingAccountId,ParameterValue=${{env.AWS_TOOLING_ACCOUNT_ID}} \
-          --region ${{ env.AWS_REGION }})
+            --stack-set-name ${{env.CROSS_ACCOUNT_STACK_SET_NAME}} \
+            --template-url https://deployment-template.s3.${{ env.AWS_REGION }}.amazonaws.com/cross-account-roles.yaml \
+            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
+            --permission-model SERVICE_MANAGED \
+            --auto-deployment Enabled=true,RetainStacksOnAccountRemoval=false \
+            --call-as DELEGATED_ADMIN \
+            --parameters ParameterKey=ToolingAccountId,ParameterValue=${{env.AWS_TOOLING_ACCOUNT_ID}} \
+            --region ${{ env.AWS_REGION }} \
+            --query "OperationId" --output text)
           
           echo "Waiting for operation $OP_ID to complete..."
 
@@ -102,10 +104,11 @@ jobs:
               --stack-set-name ${{env.CROSS_ACCOUNT_STACK_SET_NAME}} \
               --operation-id $OP_ID \
               --call-as DELEGATED_ADMIN \
+              --region ${{ env.AWS_REGION }} \
               --query "StackSetOperation.Status" --output text)
             
             if [ "$STATUS" == "SUCCEEDED" ]; then
-              echo "Instances created successfully."
+              echo "StackSet created successfully."
               break
             elif [[ "$STATUS" == "FAILED" || "$STATUS" == "STOPPED" ]]; then
               echo "Creation failed with status: $STATUS"
@@ -117,23 +120,21 @@ jobs:
 
           echo "Creating initial instances to OrganizationalUnitId=${{env.AWS_ORGANIZATIONAL_UNIT_ID}}"
           aws cloudformation create-stack-instances \
-          --stack-set-name ${{env.CROSS_ACCOUNT_STACK_SET_NAME}} \
-          --regions ${{ env.AWS_REGION }} \
-          --deployment-targets OrganizationalUnitIds='["${{env.AWS_ORGANIZATIONAL_UNIT_ID}}"]' \
-          --call-as DELEGATED_ADMIN \
-          --operation-preferences FailureToleranceCount=0,MaxConcurrentCount=1
+            --stack-set-name ${{env.CROSS_ACCOUNT_STACK_SET_NAME}} \
+            --regions ${{ env.AWS_REGION }} \
+            --deployment-targets OrganizationalUnitIds='["${{env.AWS_ORGANIZATIONAL_UNIT_ID}}"]' \
+            --call-as DELEGATED_ADMIN \
+            --operation-preferences FailureToleranceCount=0,MaxConcurrentCount=1
           
         else
           echo "StackSet already exists. Updating template..."
           aws cloudformation update-stack-set \
             --stack-set-name ${{env.CROSS_ACCOUNT_STACK_SET_NAME}} \
             --template-url https://deployment-template.s3.${{ env.AWS_REGION }}.amazonaws.com/cross-account-roles.yaml \
-            --output json \
             --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
             --permission-model SERVICE_MANAGED \
             --auto-deployment Enabled=true,RetainStacksOnAccountRemoval=false \
             --call-as DELEGATED_ADMIN \
             --parameters ParameterKey=ToolingAccountId,ParameterValue=${{env.AWS_TOOLING_ACCOUNT_ID}} \
-            --region ${{ env.AWS_REGION }} 
+            --region ${{ env.AWS_REGION }}
         fi
-        
